repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
        exclude: templates/.*
      - id: check-case-conflict
      - id: check-yaml
      - id: check-json
        exclude: .vscode/.*
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy (via uv)
        name: mypy (via uv)
        entry: uv run mypy
        language: system
        types: [python]
        pass_filenames: true
      - id: pyright (via uv)
        name: pyright (via uv)
        entry: uv run pyright
        language: system
        types: [python]
        pass_filenames: true
