name: Lint Code

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # Run daily at 6 AM UTC
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - tests/**"
      - ".github/**"
      - "pyproject.toml"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          version: "0.8.14"

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run pre-commit
        run: uv run pre-commit run --all-files
